### PR TITLE
Basic Image Upload Functionality

### PR DESCRIPTION
**Pull request by sai-prasanna**
I have added basic image upload functionality

I have taken javascript from http://benfoster.io/blog/pagedown-markdown-editor-custom-image-dialog

And used bits of djanog-ckeditor image upload code to create this functionality.

Currently it creates a jquery ui dialogue and uses jquery ajaxuploader to upload files.

No resize functionality.

And I have removed pagedown submodule and added js directly.

### CODE REVIEW

**Comment by jonearley** [comment]
@timmyomahony It would be great if basic image uploading was merged.

**Comment by timmyomahony** [comment]
Apologies for the late reply to this.  At the moment, this changes/adds way too much of the library but I'm going to look into adding this possibly as a separate library or something.

**Comment by sai-prasanna** [comment]
How will you add it as separate module? (btw, i don't even remeber the changes that I did ,because it has been more than a year)

**Comment by timmyomahony** [comment]
I'm not sure, I'll have to think about it. It's too bespoke a change at the moment to be merged.

**Pull request closed without merging**
