### PR TITLE
Make media on AdminPagedownWidget lazy

### PR DESCRIPTION
**Pull request by stefanw**
This avoids resolving static files on import which may fail if static files are not in manifest when using ManifestStaticFilesStorage.

I had this problem when running `collectstatic` to build a manifest file. Before the management command could do its thing and create the manifest the import machinery imported `pagedown` and tried to resolve the static file via manifest which then failed. The lazy loading avoids this.

### CODE REVIEW

**Comment by timmyomahony** [comment]
Interesting. I don't have much experience with this but I'll check it out thanks.

**Comment by stefanw** [comment]
Hi @timmyomahony, you are using a `_media` property in `PagedownWidget`, so this pattern should look familiar.

This change has no impact on other functionality, as it is just lazy evaluation of widget media like on `PagedownWidget` as opposed to evaluation on import time.

I would appreciate a release, if you find the time.

**Comment by quantum5** [comment]
I don't think this works. I think it prevents the assets on the base widget from loading.

**Comment by stefanw** [comment]
@quantum5 Yes, you're right. I added the media from the super classes.

**Comment by WesleyJohnson** [comment]
@timmyomahony - Do you think you could get this merged in? We're running into the same issue and the PR fixed it for us as well. Thanks! 👍  👍

**Comment by timmyomahony** [comment]
Hey, apologies for the delay, I'll check this out now

**Comment by WesleyJohnson** [comment]
@timmyomahony - Any updates?

**Comment by timmyomahony** [comment]
Sorry @WesleyJohnson , haven't gotten to it yet. I'm going to get through all the PRs and issues ASAP and update the library.

**Comment by timmyomahony** [comment]
I'm pulling this in as it's a straight forward change but I'm just wondering if anyone can suggest how to replicate this issue. I can't get it to replicate locally and I'd like to write a test case for it

**Pull request merged**
